version: '3.8'
services:
  backend-node:
    build: ./backend-node
    ports:
      - "3000:3000"
    volumes:
      - ./backend-node:/app

  backend-python:
    build: ./backend-python
    ports:
      - "5000:5000"
    volumes:
      - ./backend-python:/app

  frontend-react:
    build: ./frontend-react
    ports:
      - "3001:3001"
    volumes:
      - ./frontend-react:/app
    environment:
      - CHOKIDAR_USEPOLLING=true